### PR TITLE
Truncate names

### PR DESCRIPTION
**Pull request by SodanWT**
Hi Rico, thank you for your commit concerning the issue #60.
I dug a little bit more in the code, and found a way to resolve it without all the fist names being underlined as if they were preferred names.
As I am not a developer, my solution is certainly not the right one, so feel free to change whatever you want to keep your quality standard.
As this is my first code on GitHub, maybe the pull request is not the right way to share my solution. Just tell me how to do so :)

### CODE REVIEW

**Comment by magicsunday** [comment]
So what was wrong with my fix regarding the preferred first name? If none of the names contains an asterix the first one is used as primary given name. This one gets underlined. Was this not correct?

**Comment by SodanWT** [comment]
Hi, when there is no preferred name, the first name was underlined. But in webtrees, only the preferred names are underlined, so this made confusion with the other pages of webtrees. The other reason is that names were truncated starting with the first ones leaving the last ones unchanged if not necessary, but the last ones are the less known so they should be the first to be truncated.

**Comment by SodanWT** [comment]
I see that my commit 9444e5b8def4ad780efba63b2753fbfeb85d3cc1 has been included in the pull request, this was not intended. Dismiss it. I'll check how to remove it.

**Comment by SodanWT** [comment]
The new fix for #60 by @magicsunday is way better than mine. Happy to close this pull request

**Pull request closed without merging**
